---
apiVersion: v1
kind: Service
metadata:
  name: back-service
  labels:
    app: rps
spec:
  ports:
    - port: 5002
      protocol: TCP
      targetPort: 5002
      nodePort: 5002
  selector:
    app: rps
    tier: back
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: back-service
  labels:
    app: rps
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rps
        tier: back
    spec:
      containers:
        - image: shsnail/softdef-rps-user:latest
          name: back-service
          ports:
            - containerPort: 5002
