---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
  labels:
    app: rps
spec:
  ports:
    - port: 5003
      protocol: TCP
      targetPort: 5003
      nodePort: 5003
  selector:
    app: rps
    tier: bot
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bot-service
  labels:
    app: rps
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rps
        tier: bot
    spec:
      containers:
        - image: shsnail/softdef-rps-user:latest
          name: bot-service
          ports:
            - containerPort: 5003
