---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: rps
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 5000
  selector:
    app: rps
    tier: front
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-service
  labels:
    app: rps
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rps
        tier: front
    spec:
      containers:
        - image: shsnail/softdef-rps-front:latest
          name: front-service
          ports:
            - containerPort: 5000
