---
apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: rps
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 30000
  selector:
    app: rps
    tier: front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-service
  labels:
    app: rps
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rps
      tier: front
  template:
    metadata:
      labels:
        app: rps
        tier: front
    spec:
      containers:
        - image: shsnail/softdef-rps-front:latest
          imagePullPolicy: Always
          name: front-service
          ports:
            - containerPort: 5000
