---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: rps
spec:
  ports:
    - port: 5001
      protocol: TCP
      targetPort: 5000
  selector:
    app: rps
    tier: user
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: rps
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rps
        tier: user
    spec:
      containers:
        - image: shsnail/softdef-rps-user:latest
          name: user-service
          env:
            - name: FRONT_IP
              value: front-service:5000
            - name: USER_IP
              value: user-service:5001
            - name: BACK_IP
              value: back-service:5002
            - name: BOT_IP
              value: bot-service:5003
          ports:
            - containerPort: 5001
